### ISSUE TITLE
README Instructions?

### ISSUE THREAD

**Issue by JoshLind** [jasonkresch/protect#1]
Hi Jason,

Just came across this repo; what is the current state of the implementation and can the README be updated to reflect any possible instructions for running things?

Many thanks,
Josh

**Comment by jasonkresch** [comment]
Hi Josh,

The project is currently undergoing a design overhaul and is not currently deployable in a distributed manner. I am in the process of updating this project such that it will allow running each of the server nodes on a separate machine separated by an asynchronous network. This will require some redesign of the protocols, however. I will update this issue once that has been done.  Thank you for your interest in the project.

Sincerely,

Jason

**Comment by jasonkresch** [comment]
Hello Josh, I have updated the readme which now includes instructions for deploying the system. It is now in a runnable state, but recovery from crashes and persisted state is not finished.
