### ISSUE TITLE
Missing certificate generation script

### ISSUE THREAD

**Issue by DanielMorales9** [jasonkresch/protect#14]
Hi Jason, 

I was following the tutorial and I got stuck when issuing client and server certificates.  I could not find the following ``issue-server-certificates.sh``,  ``issue-client-certificates.sh`` scripts. Could you provide me with some instructions on how to create those by myself? 

Thank you.

**Comment by nfroidevaux** [comment]
Hi, I had the same problem and wrote the following "issue-server-certificates.sh" and it seems to work:
```
#!/bin/sh
export CA_DIR="config/ca"
export KEY_DIR="config/server/keys/"
export CERT_DIR="config/server/certs"
java -classpath ../pross-server/target/pross-server-1.0-SNAPSHOT.jar com.ibm.pross.server.app.CertificateAuthorityCli $CA_DIR $KEY_DIR $CERT_DIR true
```

**Comment by kylesteinhauer** [comment]
Faced the exact same problem. Thanks @nfroidevaux , that was exactly what I was looking for!

**Comment by jasonkresch** [comment]
@nfroidevaux
Thank you. I apparently never added those files and lost them. Thank you for regenerating that script. I have also re-created the issue-client-certificates script, which is identical except it contains a parameter of "false".
